apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: testing-k8s-vote-app
  name: postgres-deployment
spec:
  template:
    metadata: 
      labels: 
        app: testing-k8s-vote-app
        name: postgres-pod
      name: postgres-pod
    spec: 
      containers: 
        - 
          image: postgres:9.4
          name: postgres-container
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
          ports: 
            - 
              containerPort: 5432
  replicas: 1
  selector:
    matchLabels:
      app: testing-k8s-vote-app
      name: postgres-pod
    

