apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: testing-k8s-vote-app
    name: redis-service
  name: redis
spec: 
  ports: 
    - 
      port: 6379
      targetPort: 6379
  selector: 
    app: testing-k8s-vote-app
    name: redis-pod
  type: ClusterIP

