apiVersion: v1
kind: Pod
metadata:
        name: redis-pod
        labels:
                name: redis-pod
                app: testing-k8s-vote-app

spec:
        containers:
                - name: redis-container
                  image: redis
                  ports:
                          - containerPort: 6379
                
