apiVersion: v1
kind: Service
metadata:
        name: redis
        labels:
                name: redis-service
                app: testing-k8s-vote-app

spec:
        type: ClusterIP
        ports:
                - targetPort: 6379
                  port: 6379
        selector:
                name: redis-pod
                app: testing-k8s-vote-app


                  
