apiVersion: v1
kind: Pod
metadata:
        name: result-app-pod
        labels:
                name: result-app-pod
                app: testing-k8s-vote-app

spec:
        containers:
                - name: result-app-container
                  image: dockersamples/examplevotingapp_result
                  ports:
                          - containerPort: 80
                
