apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: testing-k8s-vote-app
    name: result-app-service
  name: result-app-service
spec: 
  ports: 
    - 
      port: 80
      targetPort: 80
  selector: 
    app: testing-k8s-vote-app
    name: result-app-pod
  type: LoadBalancer

