apiVersion: v1
kind: Service
metadata:
        name: voting-app-service
        labels:
                app: testing-k8s-vote-app

spec:
        type: LoadBalancer
        ports:
                - targetPort: 80
                  port: 80
        selector:
                name: voting-app-pod
                app: testing-k8s-vote-app

                  
