apiVersion: v1
kind: Pod
metadata:
        name: voting-app-pod
        labels:
                name: voting-app-pod
                app: testing-k8s-vote-app

spec:
        containers:
                - name: voting-app-container
                  image: dockersamples/examplevotingapp_vote
                  ports:
                          - containerPort: 80
                
