apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: testing-k8s-vote-app
  name: voting-app-deployment
spec:
  template:
    metadata:
      labels: 
        app: testing-k8s-vote-app
        name: voting-app-pod
      name: voting-app-pod
    spec: 
      containers: 
        - 
          image: dockersamples/examplevotingapp_vote
          name: voting-app-container
          ports: 
            - 
              containerPort: 80

  replicas: 1
  selector:
    app: testing-k8s-vote-app
    name: voting-app-pod

